config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  post '/rate' => 'rater#create', :as => 'rate'
  devise_for :users, :controllers => { :registrations => "user_registrations" }

  resources :users

  get 'users/sign_in'

  get 'users/show'

	resources :orders, only: [:index, :show, :create, :destroy]
  
  get 'orders/index'

  resources :products do
    resources :comments
  end

  post 'payments/create'
  
  get 'products/index'

  get 'products/new'

  get 'products/show'

  post 'static_pages/thank_you'

  get 'static_pages/about'

  get 'static_pages/contact'

  root 'static_pages#landing_page'

  mount ActionCable.server => '/cable'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json

  def landing_page
     @products = Product.limit(3)    
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  def thank_you
  @name = params[:name]
  @email = params[:email]
  @message = params[:message]
  ActionMailer::Base.mail(:from => @email,
      :to => 'k.santro@posteo.de',
      :subject => "A new contact form message from #{@name}",
      :body => @message).deliver_now
  end


  

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :image_url, :color, :price)
    end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<div class="page-header">
  <h1>About cozy Surfers <small id="small"> Learn more about the Berlin Surf Community</small></h1>
  <p>Berlin has a big community of surfers but not enough surf shops and no meeting spot. We wanted to change that and create cozy Surfers. Here you can connect with other surfers in Berlin, share experiences about surf trips, sell or buy surf boards and order surf equipment.</p>
</div>

<div class="row">
  <div class="col-sm-6 col-md-4">
    <div class="thumbnail">
      <%= image_tag("fixBoard.jpg", size: "400x400", class: "img-responsive") %>
      <div class="caption">
        <h3>The Community</h3>
        <p>You want to connect with other surfers in Berlin and hang out? Or plan surf trips together with friends? Join our community of cozy Surfers in Berlin and have all the advantages of a membership. </p>
        <%= link_to 'login', new_user_session_path, class: "btn btn-primary", id: "button" %>
        <%= link_to 'BECOME A MEMBER', new_user_session_path, class: "btn btn-primary", id: "button" %>
      </div>
    </div>
  </div>
  <div class="col-sm-6 col-md-4">
    <div class="thumbnail">
      <%= image_tag("workshop.jpg", size: "400x400", class: "img-responsive") %>
      <div class="caption">
        <h3>Your Surf Shop</h3>
        <p>In our online Surf Shop you can find any equipment for surfing. You can sell your own boards and other things as well.</p>
        <%= link_to 'SURF SHOP', products_path, class: "btn btn-primary", id: "button" %>
        <%= link_to 'SELL SOMETHING HERE', products_new_path, class: "btn btn-primary", id: "button" %>
      </div>
    </div>
  </div>
  <div class="col-sm-6 col-md-4">
    <div class="thumbnail">
      <%= image_tag("boardDesign.jpg", size: "400x400", class: "img-responsive") %>
      <div class="caption">
        <h3>Events</h3>
        <p>Many events about surfing are happening in Berlin and elsewhere. Come and find out, if there is something for you. Meet cool people in your City and never miss an event again!</p>
        <%= link_to 'REGISTER FOR EVENT', new_user_session_path, class: "btn btn-primary", id: "button" %>
        <%= link_to 'SEE MORE', root_path, class: "btn btn-primary", id: "button" %>
      </div>
    </div>
  </div>
</div>

app/views/static_pages/contact.html.erb
    <div class="container" id="contact">
      <h1>Contact Us</h1>
      <%= flash[:notice] %>

      <p>If you have a question, please feel free to write us a message or like us on facebook.</p>
      <%= form_tag("/static_pages/thank_you") do %>
      <div class="row">
        <div class="col-xs-6 col-md-4">
        </div> <!-- col-xs-6 end -->
        <div class="col-xs-12 col-md-8">
          <form action="/login" method="post" name="login">
            <div class="form-group">
              <%= text_area_tag :message, nil, class: "form-control", placeholder: "Write me a message here...", style: "resize:none", cols: "40", rows:"5", id: "message", required: "required", minlength: 10, name: "message", title: "enter your message" %>
              <p id="visible-comment"></p>
            </div> <!-- form group end -->
            <div class="form-group">
              <%= text_field_tag :email, nil, class: "form-control", placeholder: "for.example@mail.de", type: "email", name: "email", title: "enter your email", id: "email", required: "required", minlength: 5 %>
            </div> <!-- form group end -->
            <div class="form-group">
              <%= text_field_tag :name, nil, class: "form-control", placeholder: "Name", type: "name", id: "name", required: "required", minlength: 1, name: "name", title: "enter your name" %>
            </div> <!-- form group end -->
            <div class="form-group">
              <%= submit_tag "Send", class: "btn btn-default btn-lg", type: 'submit', id: 'button-default' %> 
            </div>
              <% end %>
          </form>
        </div> <!-- col-xs-12 end -->
      </div> <!-- row end -->
      <div class="stalker-poster">
        <h3><span class="glyphicon glyphicon-map-marker"></span>  Where can you find us?</h3>
        <p>Come check out our Spot <strong>Tempelhofer Fulgfeld</strong> in Tempelhof</p>
        <div id="map"></div>
      </div> <!-- stalker poster end -->

    </div> <!-- contact container end -->

app/views/static_pages/landing_page.html.erb
    <div class="hidden-xs"> <!-- div hides carousel on small phones -->
      <div class="container-fluid">
        <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
          <!-- Indicators -->
          <ol class="carousel-indicators">
            <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
            <li data-target="#carousel-example-generic" data-slide-to="1"></li>
            <li data-target="#carousel-example-generic" data-slide-to="2"></li>
          </ol>
          <!-- Wrapper for slides -->
          <div class="carousel-inner" role="listbox"> 
          <% @products.each do |product| %>    
					<div class="item<%= " active" if product == @products.first %>">
							<%= image_tag(product.image_url, class: "carousel-pair") %>
              <div class="carousel-pair"><%= product.description %> </div>
                
              <div class="carousel-caption">
                <%= product.name %>
              </div> 
            </div> <!-- item active end -->
       			<% end %>
          </div> <!-- carousel-inner end -->
          <!-- Controls -->
          <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
          <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
          </a>
          <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
          <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
          </a>
        </div> <!-- carousel slide end -->
      </div> <!-- container fluid end -->
    </div>  <!-- hidden xs end -->

<% cache do %>
<div class="jumbotron">
  <h1>Welcome to cozy Surfers Berlin</h1>
  <h2>We connect the community of Surfers in Berlin and provide you with Surf Equipment</h2>
  <p><%= link_to 'About', static_pages_about_path, class: "btn btn-default btn-lg", id: "button-default" %></p>
</div>
<% end %>

app/views/static_pages/thank_you.html.erb
<div class="panel panel-default">
  <div class="panel-body">
    <h2>Thanks for contacting us. We will get back to you as soon as possible.</h2>
  </div><!-- / panel-body -->
</div><!-- / panel -->

<div class="thankyou">
<%= image_tag("bike.jpg", class: "img-responsive", id: "bike-thank-you") %>
</div>