config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  post '/rate' => 'rater#create', :as => 'rate'
  devise_for :users, :controllers => { :registrations => "user_registrations" }

  resources :users

  get 'users/sign_in'

  get 'users/show'

	resources :orders, only: [:index, :show, :create, :destroy]
  
  get 'orders/index'

  resources :products do
    resources :comments
  end

  post 'payments/create'
  
  get 'products/index'

  get 'products/new'

  get 'products/show'

  post 'static_pages/thank_you'

  get 'static_pages/about'

  get 'static_pages/contact'

  root 'static_pages#landing_page'

  mount ActionCable.server => '/cable'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord
	validates :name, presence: true
	has_many :orders
	has_many :comments, :dependent => :destroy 
	
	def average_rating
  	comments.average(:rating).to_f
	end

	def highest_rating_comment
  	comments.rating_desc.first
	end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  if :development
    def index
      if params[:q]
        search_term = params[:q]
        @products = Product.where("name LIKE ?", "%#{search_term}%")
      else
        @products = Product.paginate(:page => params[:page], :per_page => 5)
      end
    end
  else
    def index
      if params[:q]
        search_term = params[:q]
        @products = Product.where("name ilike ?", "%#{search_term}%")
      else
        @products = Product.paginate(:page => params[:page], :per_page => 5)
      end
    end
  end

  def landing_page
    if params[:q]
      search_term = params[:q]
      @products = Product.where("name LIKE ?", "%#{search_term}%")
    else
      @products = Product.all
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @comments = @product.comments.order("created_at DESC")
    @comments = Comment.paginate(:page => params[:page], :per_page => 5)
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :image_url, :color, :price)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
  def cache_key_for_products
    count          = Product.count
    max_updated_at = Product.maximum(:updated_at).try(:utc).try(:to_s, :number)
    "products/all-#{count}-#{max_updated_at}"
  end
end

app/views/products/_form.html.erb
<%= form_for(product) do |f| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="input-group">
    <%= f.text_field :name, type: "text", class: "form-control", aria_label: "Name", placeholder: "Name of your Product" %>
  </div>

  <div class="input-group">
    <%= f.label :description, class: "input-group-addon" %>
    <%= f.text_area :description, type: "text", class: "form-control", aria_label: "Product description", placeholder: "Describe your Product" %>
  </div>

  <div class="input-group">
    <%= f.label :image_url, class: "input-group-addon" %>
    <%= f.text_field :image_url, type: "text", class: "form-control", aria_label: "Image", placeholder: "Image url here" %>
  </div>

  <div class="input-group">
    <%= f.label :color, class: "input-group-addon" %>
    <%= f.text_field :color, class: "form-control", placeholder: "Enter the Color of your Product" %>
  </div>

  <div class="input-group">
    <span class="input-group-addon">€</span>
    <%= f.text_field :price, type: "text", class: "form-control", aria_label: "Amount (to the nearest dollar)", placeholder: "Price in Euro" %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/_product.html.erb
<div class="col-sm-6 col-md-4">
    <div class="thumbnail">
      <div class="caption">
        <% cache product do %>
          <%= image_tag(product.image_url, size: "400x400", class: "img-responsive") %>
          <h3><%= product.name %></h3>
          <p><%= product.description %></p>
          <p><%= product.color %></p>
          <p><%= product.price %></p>
          <div class="btn btn-default"><%= link_to 'Buy', orders_path, id: "button-default" %></div>
          <div class="btn btn-info"><%= link_to 'Show', product, id: "button-default" %></div>
          <div class="btn btn-default"><%= link_to 'Edit', edit_product_path(product), id: "button-default" %></div>
          <div class="btn btn-danger"><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' }, id: "button-default" %></div>
        <% end %>
      </div>
    </div>
  </div>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product, class: "btn btn-default" %> 
<%= link_to 'Back', products_path, class: "btn btn-default" %>

app/views/products/index.html.erb
<div class="jumbotron" id="surfshop">
  <div class="container">
    <h1>Surf Shop</h1>
    <p>Browse for your perfect surf equipment. You can also sell your boards and eqipment here.</p>
  </div>
</div>


<div class="row">
	<% @products.each do |product| %>		  
		<%= render product %>
	<% end %>
</div>

<br>
<%= will_paginate @products %>

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path, class: "btn btn-default" %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<% cache @product do %>
<div class="row" data-product-id="<%= @product.id %>">
 <div class="col-xs-12 col-md-8">
   <%= image_tag(@product.image_url, size: "800x800", class: "img-responsive img-zoom", id: "product-img", data_zoom_image: @product.image_url) %>
 </div>
 <div class="col-xs-6 col-md-4">
   <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
 <div class="panel panel-default">
   <div class="panel-heading" role="tab" id="headingOne">
     <h4 class="panel-title">
       <a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
         <%= @product.name %>
       </a>
     </h4>
   </div>
   <div id="collapseOne" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="headingOne">
     <div class="panel-body">
       <%= @product.description %>
     </div>
   </div>
 </div>
 <div class="panel panel-default">
   <div class="panel-heading" role="tab" id="headingTwo">
     <h4 class="panel-title">
       <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
         Details
       </a>
     </h4>
   </div>

   <div id="collapseTwo" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingTwo">
     <div class="panel-body">
       <%= @product.description %>
       <p>Average Rating: <div class="rated" data-score="<%= @product.average_rating %>" id="average-rating"></div> </p>
       <p>
 <strong>Color:</strong>
 <%= @product.color %>
</p>

<p>
 <strong><span class="glyphicon glyphicon-eur" aria-hidden="true"></span></strong>
 <%= @product.price %>
 <%= form_tag "/payments/create" do %>
   <%= render partial: "shared/stripe_checkout_button" %>
 <% end %>

</p>
     </div>
   </div>
 </div>
</div>
 <% end %>

 </div>
</div>


<div class="alert alert-info" style="display:none" role="alert">A new comment was posted!</div>

<h2>Comments</h2>
 <div class="product-reviews">
   <%= render @product.comments %>
 </div>

<%= render "comments/form" %>

<%= will_paginate @comments %>    






<%= link_to 'Edit', edit_product_path(@product), class: "btn btn-default" %> 
<%= link_to 'Back', products_path, class: "btn btn-default" %>