config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  post '/rate' => 'rater#create', :as => 'rate'
  devise_for :users, :controllers => { :registrations => "user_registrations" }

  resources :users

  get 'users/sign_in'

  get 'users/show'

	resources :orders, only: [:index, :show, :create, :destroy]
  
  get 'orders/index'

  resources :products do
    resources :comments
  end

  post 'payments/create'
  
  get 'products/index'

  get 'products/new'

  get 'products/show'

  post 'static_pages/thank_you'

  get 'static_pages/about'

  get 'static_pages/contact'

  root 'static_pages#landing_page'

  mount ActionCable.server => '/cable'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CozySurfers</title>
    <%= csrf_meta_tags %>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<!--     <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
 -->    
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track'=> true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track'=> true %>
    <!--<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script> -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script type="text/javascript" src="https://js.stripe.com/v2/"></script>
  </head>

  <body data-spy="scroll" data-target=".navbar">
    <div class="page-wrap">
    <div id="fb-root"></div>
    <script>(function(d, s, id) {
      var js, fjs = d.getElementsByTagName(s)[0];
      if (d.getElementById(id)) return;
      js = d.createElement(s); js.id = id;
      js.src = "//connect.facebook.net/de_DE/sdk.js#xfbml=1&version=v2.7";
      fjs.parentNode.insertBefore(js, fjs);
      }(document, 'script', 'facebook-jssdk'));</script>

  	<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid" id="customnav">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to '', root_path, class: "btn btn-default btn-lg glyphicon glyphicon-home" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to 'Surf Shop', products_path %></li>
        <li><%= link_to 'About', static_pages_about_path %></li>
        <li><%= link_to 'Contact', static_pages_contact_path %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">More<span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to 'Contact', static_pages_contact_path %></li>
            <li><%= link_to 'SurfShop', products_path %></li>
            <li><%= link_to 'Orders', orders_index_path %></li>
            <li role="separator" class="divider"></li>
            <li><a href="https://www.instagram.com/kaja_tiger/">Instagram</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="https://github.com/kajatiger">Github</a></li>
          </ul>
        </li>
        
      </ul>  
      
        <ul class="nav navbar-nav navbar-right">
          <li>
            <% if user_signed_in? %>
              <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
            <% else %>
              <%= link_to('Login', new_user_session_path) %>
            <% end %>
          </li>

         <li>
           <% if admin_user_signed_in? %>
             <%= link_to('Logout Admin', destroy_admin_user_session_path, :method => :delete) %>
           <% else %>
             <%= link_to('Login Admin', new_admin_user_session_path) %>
           <% end %>
         </li>
          <li><%= link_to 'New Product', new_product_path %></li>
              <%= form_tag("/products", method: "get", class: "navbar-form navbar-left") do %>
              <%= search_field_tag(:q, params[:q], class: "form-control", placeholder: "Search") %>
              <%= submit_tag('FIND', class: "btn btn-default btn-lg", id: "button-default") %>
              <% end %> 
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
    </nav>
  
    <%= yield %>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    
   </div> <!-- page wrap end --> 
    <footer class="site-footer">
      <div class="follow-twitter">
        <a href="https://twitter.com/AlizeNero" class="twitter-follow-button" data-show-count="false" data-size="large" data-show-screen-name="false">Follow @AlizeNero
        </a>
      </div> <!-- follow twitter end -->
      <div class="fb-like" data-href="http://kaja.bitballoon.com/" data-width="40px" data-layout="button" data-action="like" data-show-faces="true" data-share="false">
      </div>  
      <div class="copyright">
        <p>&copy; 2016 Cozy Surfers Berlin</p>
      </div> <!-- copyright end -->
  		
		</footer>
  </body>
</html>